### ISSUE TITLE
Please provide more examples.

### ISSUE THREAD

**Issue by Conglang** [shish/sikulpy#18]
Please provide more usage examples. Some results are differed between sikulpy and the Java sikulix, wondering what caused the difference, default setting difference? Don't have much clue.
For example,
I have tried the Helloworld example on sikulpy but it can't find a match. 
Tried type in a region and it generated several errors.
Tried several other bigger image with lower similarity setting, matches found, but clicking is not working. I can see mouseMove in debugging message but nothing happend.
Really confused, don't know if I make a mistake in script or setting or anything else. Hope there could be more examples to follow. Thank you.

**Comment by shish** [comment]
Can you provide some examples of code which works in sikulix but not sikulpy? The goal is that they are 1:1 compatible and anything else is a bug

**Comment by Conglang** [comment]
Hi shish, sorry for the late reply. 
I can't reproduce some of the problems I said earlier, guess those were because of my misuse of your library or byproduct of the one problem below.
Only one problem remain, the screen size is wrong.

For example, the hello world example of sikulix. Find the start menu button on Windows 7.
Python 2 code:
```python
from sikuli import *

s = Screen(0)
print s
r = Region(0,0,2880,1880)
isfind = s.exists(Pattern("start_button.png").similar(0.9))
print isfind
```
Result:
```
In [15]: run find_start_button.py
Screen(0, 0, 1448, 905)
None
```

Notice my screen resolutioin is 2880 x 1880, which is different from the Screen's value sikulpy generates. The environment is Windows 7 x64, on a virtual machine on the mac, don't know whether this matters or not.
Guess the reason it didn't find the start button is because it's on the left bottom corner, outside of the region.

So that's the one problem. Thank you!

**Comment by shish** [comment]
I expect that the retina display is confusing things there (some functions work with software pixels and some work with hardware pixels). I've got the conversions working right for the host OS, but I'm not sure how the retina display is presented to the OS inside the VM (ie, does Windows see a huge screen with regular DPI, or a regular-size screen at high-DPI...)

I'm working on a retina macbook myself, so I shall see if I can get a win7 VM set up :)

**Comment by shish** [comment]
What VM software are you using?

Also FWIW `Screen(0, 0, 1440, 900)` is expected based on how sikulix treats high-DPI displays on OSX - everything is downscaled to run at software resolution rather than hardware resolution

**Comment by Conglang** [comment]
Hi shish, I'm using Parallels Desktop on mac.

**Comment by shish** [comment]
kk, looks like it has a 14 day trial, and I'm going to be on a business trip for the next 17 days, so beginning the debug process today seems unwise - will keep a tab open for when I get back; and try using virtualbox to see if that has the same issue without a time limit on debugging :)

**Comment by Conglang** [comment]
Hi shish, sorry for the terribly late reply. I am desperately busy these days and have literally changed my job :) Thanks for your effort! I am more than willing to help if any more information is needed :)
