### ISSUE TITLE
State of development

### ISSUE THREAD

**Issue by wolfc01** [shish/sikulpy#2]
Hello,

simple question: wat is the state of development of this package? Before diving in I like to know if this package can be used for production usage as a part of our automatic continuous integration test tooling.

Best regards
Carl.

**Comment by shish** [comment]
The subset of the sikuli API that I personally use is pretty stable, solid, and compatible with java-sikuli (capture the screen, look for specific widgets using image recognition, click on things, type things). The parts of the sikuli API that I'm not personally using I can't guarantee, but if you have specific requests I would be happy to check and possibly help to implement them :)

**Comment by shish** [comment]
I've updated the readme with a super-summarised table, will look into getting something better :)

**Comment by shish** [comment]
Replaced the table with a bunch of Issues showing what's currently missing, so we can keep track of the journey to 100% compatibility
